// Generated by gencpp from file ee106s25/ee106s23_serviceRequest.msg
// DO NOT EDIT!


#ifndef EE106S25_MESSAGE_EE106S23_SERVICEREQUEST_H
#define EE106S25_MESSAGE_EE106S23_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ee106s25
{
template <class ContainerAllocator>
struct ee106s23_serviceRequest_
{
  typedef ee106s23_serviceRequest_<ContainerAllocator> Type;

  ee106s23_serviceRequest_()
    : request_msg()  {
    }
  ee106s23_serviceRequest_(const ContainerAllocator& _alloc)
    : request_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_msg_type;
  _request_msg_type request_msg;





  typedef boost::shared_ptr< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ee106s23_serviceRequest_

typedef ::ee106s25::ee106s23_serviceRequest_<std::allocator<void> > ee106s23_serviceRequest;

typedef boost::shared_ptr< ::ee106s25::ee106s23_serviceRequest > ee106s23_serviceRequestPtr;
typedef boost::shared_ptr< ::ee106s25::ee106s23_serviceRequest const> ee106s23_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator1> & lhs, const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request_msg == rhs.request_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator1> & lhs, const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ee106s25

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec3985f3b00d27737504bd460abc4887";
  }

  static const char* value(const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec3985f3b00d2773ULL;
  static const uint64_t static_value2 = 0x7504bd460abc4887ULL;
};

template<class ContainerAllocator>
struct DataType< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee106s25/ee106s23_serviceRequest";
  }

  static const char* value(const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request_msg\n"
;
  }

  static const char* value(const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ee106s23_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ee106s25::ee106s23_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EE106S25_MESSAGE_EE106S23_SERVICEREQUEST_H
