// Generated by gencpp from file ee106s25/ee106s23_service.msg
// DO NOT EDIT!


#ifndef EE106S25_MESSAGE_EE106S23_SERVICE_H
#define EE106S25_MESSAGE_EE106S23_SERVICE_H

#include <ros/service_traits.h>


#include <ee106s25/ee106s23_serviceRequest.h>
#include <ee106s25/ee106s23_serviceResponse.h>


namespace ee106s25
{

struct ee106s23_service
{

typedef ee106s23_serviceRequest Request;
typedef ee106s23_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ee106s23_service
} // namespace ee106s25


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ee106s25::ee106s23_service > {
  static const char* value()
  {
    return "bbbdbd457d086498a93ac52318048de7";
  }

  static const char* value(const ::ee106s25::ee106s23_service&) { return value(); }
};

template<>
struct DataType< ::ee106s25::ee106s23_service > {
  static const char* value()
  {
    return "ee106s25/ee106s23_service";
  }

  static const char* value(const ::ee106s25::ee106s23_service&) { return value(); }
};


// service_traits::MD5Sum< ::ee106s25::ee106s23_serviceRequest> should match
// service_traits::MD5Sum< ::ee106s25::ee106s23_service >
template<>
struct MD5Sum< ::ee106s25::ee106s23_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ee106s25::ee106s23_service >::value();
  }
  static const char* value(const ::ee106s25::ee106s23_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ee106s25::ee106s23_serviceRequest> should match
// service_traits::DataType< ::ee106s25::ee106s23_service >
template<>
struct DataType< ::ee106s25::ee106s23_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::ee106s25::ee106s23_service >::value();
  }
  static const char* value(const ::ee106s25::ee106s23_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ee106s25::ee106s23_serviceResponse> should match
// service_traits::MD5Sum< ::ee106s25::ee106s23_service >
template<>
struct MD5Sum< ::ee106s25::ee106s23_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ee106s25::ee106s23_service >::value();
  }
  static const char* value(const ::ee106s25::ee106s23_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ee106s25::ee106s23_serviceResponse> should match
// service_traits::DataType< ::ee106s25::ee106s23_service >
template<>
struct DataType< ::ee106s25::ee106s23_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::ee106s25::ee106s23_service >::value();
  }
  static const char* value(const ::ee106s25::ee106s23_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EE106S25_MESSAGE_EE106S23_SERVICE_H
